### ISSUE TITLE
Add “copy” button to API token UI

### ISSUE THREAD

**Issue by mikeal** [ipfs-shipyard/nft.storage#140]

**Comment by alanshaw** [comment]
Assuming this would copy the token to a different account?

**Comment by Ronak-59** [comment]
@alanshaw I think the author is referring to a button called "Copy" next to each API Key which would instantly copy that key to clipboard on click so that user can paste it wherever needed. This will help avoid users having to manually copy the whole `API Key` string. 

On mobile devices, too, it's difficult to copy entire Key as it's not visible. (Maybe that webpage is not responsive?) Implementation of "Copy" button will help with this issue too.

**Comment by alanshaw** [comment]
yeah that makes sense 🤦‍♂️

**Comment by mikeal** [comment]
The description could have been more specific, I wrote this up on my phone while you were giving a demo ☺️
