### ISSUE TITLE
Issues with "429 Error" and "Uncaught in Promise"

### ISSUE THREAD

**Issue by JacobSloan** [ipfs-shipyard/nft.storage#383]
We have an NFT Marketplace on Kucoin Community Chain https://nftsrealm.com and we use NFT.Storage. We have been having reoccurring IPFS issues and would greatly appreciate your help as soon as possible. When loading the resources (in this case the NFT data) we keep seeing a 429 error and an Uncaught in Promise error. 

<img width="960" alt="IPFS issues" src="https://user-images.githubusercontent.com/20230942/131890514-81be9096-5bef-4d6d-bd1a-69b0988f27e7.png">

**Comment by dchoi27** [comment]
Hey there - are you using the ipfs.io gateway to access your data? If so, it's been having some trouble with heavy load lately, but over the last day or so it's gotten better with additional nodes added. This isn't an NFT.Storage-specific issue per se (since it's related to retrieving data out of a specific gateway, but the data is still available via other gateways or IPFS nodes), but a lot of our users do use the ipfs.io gateway so we've been receiving some reports around this and are trying to help out. Part of the tough thing about relying on centralized infrastructure (though it's an important piece of infrastructure, and the team is working hard to make sure this gateway is more performant)! 

If not, then let us know how you're accessing the data, and we can help debug.

(btw removed tags in your OP to not spam others not day-to-day involved with the thread!)

**Comment by dchoi27** [comment]
Closing for now - feel free to reopen if needed.
