### ISSUE TITLE
ipfs CIDs are 2 characters too long for my application

### ISSUE THREAD

**Issue by nftnixie** [ipfs-shipyard/nft.storage#417]
Hi,

My applications require I fit the CID & ipfs://" within a 64 character limit.

The length of the links used with nft.storage, without "ipfs://" are 59 characters long.  Appending "ipfs://" makes it 66 characters...2 characters over the limit :(. 

Is there any way you could look into shortening the CID by 2 characters?

**Comment by aschmahmann** [comment]
@nftnixie all of the bytes in the CID are required to represent your data. However, depending on your application you could try using an alternative [multibase](https://github.com/multiformats/multibase) representation of the bytes for your CID.

IIRC the default representation you are getting is base32, so if you need something a little smaller you might want to try base36. If you needed it to be even smaller you could go for base58btc or base64.

IMO the main thing to consider when choosing a base representation is if the base is well supported in the environments you're expecting (e.g. applications like IPFS Companion, go/js-ipfs, the ipfs.io public gateways, URL bars, etc. ). The encodings listed above should be supported in all of the applications above, however sometimes case sensitive encodings can be a problem in URL bars which is why the default outputs for nft.storage are base32 encoded.

Given that base36 is all lowercase (like base32), but a little more compact it seems likely to be your best bet.

If you want to change the multibase encoding of a CID then using go-ipfs' `ipfs cid format -b=<base> <cid>` will do the job (there are libraries in Go and JS that could also help you with this). You can learn more about the CID format by exploring https://cid.ipfs.io or checking out the [spec](https://github.com/multiformats/cid).

For example, you'll notice that https://cid.ipfs.io/#bafkreignf3fdknlud4t2rlsaymnqyqouav5hu64rfmz3tlwymsc5dscgoy and https://cid.ipfs.io/#k2cwuedri8sqoo7uk4tffwfpc5ptte60jmwh790mhk2mglplpkvmml4m represent the same data but with different base encodings.

**Comment by nftnixie** [comment]
converting to a different base works perfectly.  thank you so much!
