### ISSUE TITLE
Upload metadata with existing image url?

### ISSUE THREAD

**Issue by bigchiano** [ipfs-shipyard/nft.storage#617]
Hi guys, I thought it'd be nice if I could upload metadata using an existing image URL.

As I have seen here [github.com/ipfs-shipyard/nft.storage/blob/main/packages/client/src/lib.js#L453](url) it forces one to upload metadata with the image as a blob and the response of the image comes with ipfs URI which is not much supported on some of these wallets. I would suggest returning the image with a URL that uses public HTTP gateways or at least allow to upload an image with a URL that exists and leave it that way even on the response.

**Comment by yusefnapora** [comment]
Hey @bigchiano, thanks for reaching out. We generally try to steer people away from linking to specific HTTP gateways. since they can be a single point of failure and may go down or disappear some point. Of course, you can put whatever you want into the `properties` field, but that doesn't really help with wallet support since it's not standardized.

For now if your heart is set on using HTTP URLs, I'd say your best bet is to create the metadata json manually and store it using `storeBlob`.  There's an example app called [minty](https://github.com/yusefnapora/minty) that creates metadata like this, which might help demonstrate. Minty stores IPFS URIs in the metadata, but you could easily change it to store gateway URLs instead.

Are there specific wallets that you know don't support IPFS URIs? Ideally we could make PRs or otherwise work with them to add native support.

I'm going to close the issue as we are unlikely to add this feature, but thanks for the feedback, and please keep the suggestions coming!
